### ISSUE TITLE
在1.12.2spigot服务端中依op身份执行传送指令/ewarp tp 11 出现的错误

### ISSUE THREAD

**Issue by orange1184258252** [4o4E/EWarp#2]
[16:04:29 INFO]: chengzi issued server command: /ewarp tp 11
[16:04:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ewarp' in plugin EWarp v1.0.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:682) ~[Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_411]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_411]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_411]
Caused by: java.lang.NoSuchFieldError: ENTITY_ENDERMAN_TELEPORT
        at top.e404.warp.warp.Warp.teleport$tp(Warp.kt:158) ~[?:?]
        at top.e404.warp.warp.Warp.teleport(Warp.kt:162) ~[?:?]
        at top.e404.warp.command.use.Teleport.onCommand(Teleport.kt:29) ~[?:?]
        at top.e404.warp.command.CommandManager.onCommand(CommandManager.kt:63) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot-Shutdown.jar:git-Spigot-dcd1643-e60fc34]
        ... 15 more

**Comment by 4o4E** [comment]
使用更高的版本

**Comment by orange1184258252** [comment]
你是该插件只能在像1.16.5这样的高版本服务端中使用吗，能否支持一下1.12.2

**Comment by 4o4E** [comment]
> 你是该插件只能在像1.16.5这样的高版本服务端中使用吗，能否支持一下1.12.2

没有计划
